"""Added country and person relationships

Revision ID: e6a5c37e4506
Revises: d5f849fcb806
Create Date: 2019-11-08 01:16:26.893879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6a5c37e4506'
down_revision = 'd5f849fcb806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_exist', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('birth_country_id', sa.Integer(), nullable=True),
    sa.Column('birth_place', sa.String(length=20), nullable=True),
    sa.Column('died_date', sa.DateTime(), nullable=True),
    sa.Column('died_country_id', sa.Integer(), nullable=True),
    sa.Column('died_place', sa.String(length=20), nullable=True),
    sa.Column('last_date_edition', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['birth_country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['died_country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('person_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('lastname', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='person_table_pkey')
    )
    op.drop_table('person')
    op.drop_table('country')
    # ### end Alembic commands ###
